const blogsTypes = {
    ADD_NEW_BLOG_START:'ADD_NEW_BLOG_START',
    FETCH_BLOGS_START:'FETCH_BLOGS_START',
    SET_BLOGS:'SET_BLOGS',
    DELETE_BLOG_START:'DELETE_BLOG_START',
    FETCH_BLOG_START:'FETCH_BLOG_START',
    SET_BLOG:'SET_BLOG'
    };
    
export default blogsTypes;