const designersTypes = {
    ADD_NEW_DESIGNER_START:'ADD_NEW_DESIGNER_START',
    FETCH_DESIGNERS_START:'FETCH_DESIGNERS_START',
    SET_DESIGNERS:'SET_DESIGNERS',
    DELETE_DESIGNER_START:'DELETE_DESIGNER_START',
    FETCH_DESIGNER_START:'FETCH_DESIGNER_START',
    SET_DESIGNER:'SET_DESIGNER'
    };
    
export default designersTypes;